"""add column is_admin in User model

Revision ID: 5ddb62d61a18
Revises: f4d2e42e6c3e
Create Date: 2025-04-06 15:01:12.761184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddb62d61a18'
down_revision: Union[str, None] = 'f4d2e42e6c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'is_admin')
    # ### end Alembic commands ###
